config/routes.rb
# Add routes for your plugin, like so:
#
# Workarea::Admin::Engine.routes.draw do
#   resources :inventory_notifications
# end
#
Workarea::Storefront::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    get 'inventory_notifications/:product_id/new' => 'inventory_notifications#new', as: :new_product_inventory_notification
    post 'inventory_notifications/:product_id' => 'inventory_notifications#create', as: :create_product_inventory_notification
  end
end

app/models/workarea/inventory/policies/allow_notify.rb
module Workarea
  module Inventory
    module Policies
      class AllowNotify < Standard
        def displayable?
          true
        end
      end
    end
  end
end

app/models/workarea/inventory_notification.rb
module Workarea
  class InventoryNotification
    include ApplicationDocument

    field :product_id,  type: String
    field :sku,         type: String
    field :email,       type: String
    field :sent_at,     type: DateTime

    validates :product_id, presence: true
    validates :sku, presence: true
    validates :email, presence: true,
                      email: true

    index(sku: 1)

    scope :unsent, -> { where(sent_at: nil) }

    def mark_as_sent!
      update_attributes(sent_at: Time.now)
    end
  end
end

app/controllers/workarea/storefront/inventory_notifications_controller.rb
module Workarea
  class Storefront::InventoryNotificationsController < Storefront::ApplicationController
    before_action :set_product

    def new; end

    def create
      @notification = InventoryNotification.new(notification_params)

      if @notification.save
        flash[:success] = t('workarea.storefront.inventory_notifications.flash_messages.saved')
        redirect_to storefront.product_path(@product)
      else
        flash[:error] = t('workarea.storefront.inventory_notifications.flash_messages.error')
        render :new
      end
    end

    private

      def set_product
        model = Catalog::Product.find_by(slug: params[:product_id])
        @product = Storefront::ProductViewModel.wrap(model, view_model_options)
      end

      def notification_params
        params[:notification].permit(:product_id, :sku, :email)
      end
  end
end

app/views/workarea/storefront/inventory_notifications/new.html.haml
- @title = t('workarea.storefront.inventory_notifications.new.title', product: @product.browser_title)

.signup-notification.view

  %h1= t('workarea.storefront.inventory_notifications.new.title', product: @product.browser_title)

  = form_tag create_product_inventory_notification_path(@product), method: 'post', id: 'inventory_notification_form' do

    %p= t('workarea.storefront.inventory_notifications.new.instruction')

    = hidden_field_tag "notification[product_id]", @product.id
    .property
      = label_tag "notification_sku", t('workarea.storefront.inventory_notifications.new.select_options'), class: 'property__name'
      .value= select_tag "notification[sku]", options_for_select(@product.unavailable_sku_options, params.fetch(:notification, {})[:sku]), required: true
    .property
      = label_tag "notification_email", t('workarea.admin.fields.email'), class: 'property__name'
      .value= email_field_tag "notification[email]", current_user.try(:email), class: 'text-box', required: true, placeholder: t('workarea.storefront.forms.email_placeholder')

    %p.add-to-notify-action= button_tag t('workarea.storefront.inventory_notifications.notify_me'), value: 'add_notification', class: 'button button--large'

app/views/workarea/storefront/products/_inventory_notifications.html.haml
- if product.current_sku_unavailable?
  #inventory_notifications.inventory-notifications
    .inventory-notifications__signup
      %p
        %strong= t('workarea.storefront.products.this_item_is_out_of_stock')
      %p
        = t('workarea.storefront.products.inventory_notification_prompt')
        = link_to t('workarea.storefront.products.sign_up_for_email_notification'),  storefront.new_product_inventory_notification_path(product), data: { dialog_button: '' }